[build-system]
requires = ["aero-build-tools", "setuptools", "wheel"]
build-backend = "aero_build_tools.build_meta"

[project]
name = "aeronum"
version = "0.1.0"
description = "High-performance numerical computing library with Aero backend"
authors = [
    {name = "Robert Van Arsdale", email = "robert.vanarsdale@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
keywords = ["numerical", "computing", "arrays", "linear-algebra", "performance"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Aero",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "numpy>=1.20.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-benchmark",
    "black",
    "isort",
    "mypy",
    "sphinx",
    "sphinx-rtd-theme",
]
test = [
    "pytest>=6.0",
    "pytest-benchmark",
    "numpy",
    "scipy",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "numpydoc",
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/RobVanProd/AeroNum"
Documentation = "https://aeronum.readthedocs.io"
Repository = "https://github.com/RobVanProd/AeroNum"
"Bug Tracker" = "https://github.com/RobVanProd/AeroNum/issues"

[tool.aero-build]
# Aero-specific build configuration
target = "aeronum-python"
source-dir = "src"
include-dirs = ["../src"]
link-libraries = ["aeronum"]
optimization-level = 3
features = ["python-bindings", "blas"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--verbose",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "benchmark: marks tests as benchmarks",
]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["aeronum"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "numpy.*",
    "scipy.*",
]
ignore_missing_imports = true

